receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

connectors:
  spanmetrics:
    namespace: span.metrics

processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp, spanmetrics ]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics:
      receivers: [ spanmetrics ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ loki ]
