global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269

  - job_name: services
    static_configs:
      - targets:
          - proxy-service:80
          - business-service-1:80
          - business-service-2:80
          - business-service-3:80
